
servidor5:

	HOST=127.0.0.1 PORT=9009 python3 srv5.py

cliente5:
	HOST=127.0.0.1 PORT=9009 python3 cli5.py
clean:
	@echo "No hay archivos temporales que limpiar."

servidor5_archivos:
	python3 srv_archivos_udp.py

cliente5_archivos:
	python3 cli_archivos_udp.py
